# Generated by Django 4.1.7 on 2023-10-23 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_warranty_client_warranties'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warranty',
            options={'ordering': ('item',), 'verbose_name': 'Warranty', 'verbose_name_plural': 'Warranties'},
        ),
    ]
