# Generated by Django 4.1.7 on 2023-10-23 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_warranty_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='contract',
            field=models.FileField(blank=True, null=True, upload_to='documents/contracts/'),
        ),
        migrations.AddField(
            model_name='client',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/IDs/'),
        ),
        migrations.AddField(
            model_name='client',
            name='job_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
