# Generated by Django 4.1.7 on 2023-10-23 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_client_company_client_contract_client_id_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='phone_number2',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
