# Generated by Django 4.1.7 on 2023-10-24 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_client_phone_number2'),
    ]

    operations = [
        migrations.AddField(
            model_name='warranty',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='documents/garantias/'),
        ),
    ]
