# Generated by Django 4.1.7 on 2023-10-27 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_client_date_of_birth_client_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='months_to_repay',
            field=models.IntegerField(default=1),
        ),
    ]
