# Generated by Django 4.1.7 on 2023-10-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_client_months_to_repay'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='starting_month',
            field=models.DateField(blank=True, null=True),
        ),
    ]
