# Generated by Django 4.1.7 on 2023-10-27 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_paymentplan_paid_base_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentplan',
            old_name='paid_base_amount',
            new_name='already_paid_base_amount',
        ),
        migrations.RenameField(
            model_name='paymentplan',
            old_name='paid_interest',
            new_name='already_paid_interest',
        ),
    ]
