# Generated by Django 4.1.7 on 2023-10-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_paid_base_amount_paymentplan_already_paid_base_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='remaining_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
